export default [
    'India',
    'United States',
    'United Kingdom',
    'Norway',
    'Turkey',
    'Swedan',
    'Germany',
    'Ireland',
    'France',
    'United Arab Emirates',
    'Qatar',
    'Oman',
    'Leabonan',
    'Jordan',
    'South Africa',
    'Russia',
    'South Korea',
    'Japan',
    'New Zealand',
    'Iceland',
    'Ukrain',
];